### ISSUE TITLE
compile error on raspberry pi 

### ISSUE THREAD

**Issue by adammeller** [lukbek/supla-virtual-device#10]
Hi,

I cannot complile supla-virtual-device on raspberry pi 
gcc version 4.9.2 (Raspbian 4.9.2-10)
uname -a
Linux raspberrypi 4.4.11-v7+ #888 SMP Mon May 23 20:10:33 BST 2016 armv7l GNU/Linux

I run make all
/home/pi/supla-virtual-device/src/supla-dev/Release make all

Any advice what I am doing wrong?

this is an error I got:

Invoking: Cross G++ Compiler
g++ -D__DEBUG=1 -D__SSOCKET_WRITE_TO_FILE= -D__NO_DATABASE -D__NO_USER -I/usr/src/openssl/include -I../src/json -O0 -g3 -Wall -fsigned-char -c -fmessage-length=0 -MMD -MP -MF"src/mqtt/mqtt_client.d" -MT"src/mqtt/mqtt_client.o" -o "src/mqtt/mqtt_client.o" "../src/mqtt/mqtt_client.cpp"
../src/mqtt/mqtt_client.cpp: In function ‘int mqtt_client_init(std::string, int, std::string, std::string, std::string, uint8_t, std::vector<std::basic_string<char> >&, void (*)(void**, mqtt_response_publish*))’:
../src/mqtt/mqtt_client.cpp:101:8: warning: ‘auto’ changes meaning in C++11; please remove it [-Wc++0x-compat]
   for (auto topic : topics) reconnect_state->topics.push_back(topic);
        ^
../src/mqtt/mqtt_client.cpp:101:13: error: ‘topic’ does not name a type
   for (auto topic : topics) reconnect_state->topics.push_back(topic);
             ^
../src/mqtt/mqtt_client.cpp:104:3: error: expected ‘;’ before ‘mq_client’
   mq_client = new mqtt_client();
   ^
../src/mqtt/mqtt_client.cpp:104:31: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
   mq_client = new mqtt_client();
                               ^
../src/mqtt/mqtt_client.cpp:105:49: error: expected ‘)’ before ‘;’ token
   mq_client->protocol_version = protocol_version;
                                                 ^
../src/mqtt/mqtt_client.cpp: In function ‘void reconnect_client(mqtt_client*, void**)’:
../src/mqtt/mqtt_client.cpp:201:8: warning: ‘auto’ changes meaning in C++11; please remove it [-Wc++0x-compat]
   for (auto topic : reconnect_state->topics) {
        ^
../src/mqtt/mqtt_client.cpp:201:13: error: ‘topic’ does not name a type
   for (auto topic : reconnect_state->topics) {
             ^
../src/mqtt/mqtt_client.cpp:205:1: error: expected ‘;’ before ‘}’ token
 }
 ^
../src/mqtt/mqtt_client.cpp:205:1: error: expected primary-expression before ‘}’ token
../src/mqtt/mqtt_client.cpp:205:1: error: expected ‘;’ before ‘}’ token
../src/mqtt/mqtt_client.cpp:205:1: error: expected primary-expression before ‘}’ token
../src/mqtt/mqtt_client.cpp:205:1: error: expected ‘)’ before ‘}’ token
../src/mqtt/mqtt_client.cpp:205:1: error: expected primary-expression before ‘}’ token
src/mqtt/subdir.mk:28: recipe for target 'src/mqtt/mqtt_client.o' failed
make: *** [src/mqtt/mqtt_client.o] Error 1

Regards,
Adam

**Comment by lukbek** [comment]
Hi, I suppose it is because of c++ compiler version. Automatic builds are passing ok, and I’ve just try compile it on RPi with success. Try upgrade youre os by typing 

sudo apt-get install -y --no-install-recommends \
        git \
        make \
        gcc \
        g++ \
        libssl-dev \
        ca-certificates \
        ssl-cert

**Comment by adammeller** [comment]
Hi,

In fact,  when I used newest rasbian image everything works as designed,

Thanks for help,
