### ISSUE TITLE
Problem z kompilacją

### ISSUE THREAD

**Issue by Fazik83** [lukbek/supla-virtual-device#11]
Witam,
Nie mogę skompilować svd. 
Linux orangepi3 5.10.60-sunxi64 #21.08.1 SMP Wed Aug 25 18:29:57 UTC 2021 aarch64 GNU/Linux

`Building target: supla-virtual-device
Invoking: Cross G++ Linker
g++ -L/usr/src/openssl/lib -pthread -lrt -o "supla-virtual-device" ./src/supla-client-lib/cfg.o ./src/supla-client-lib/devicechannel.o ./src/supla-client-lib/eh.o ./src/supla-client-lib/ini.o ./src/supla-client-lib/ipcsocket.o ./src/supla-client-lib/lck.o ./src/supla-client-lib/log.o ./src/supla-client-lib/proto.o ./src/supla-client-lib/safearray.o ./src/supla-client-lib/srpc.o ./src/supla-client-lib/sthread.o ./src/supla-client-lib/supla-client.o ./src/supla-client-lib/supla-socket.o ./src/supla-client-lib/tools.o  ./src/mqtt/mqtt.o ./src/mqtt/mqtt_client.o ./src/mqtt/mqtt_pal.o  ./src/accept_loop.o ./src/channel-io.o ./src/client_device.o ./src/client_publisher.o ./src/client_subscriber.o ./src/common.o ./src/common_dht_read.o ./src/devcfg.o ./src/devconnection.o ./src/gpio.o ./src/ipcctrl.o ./src/mcp23008.o ./src/pi_2_dht_read.o ./src/pi_2_mmio.o ./src/supla-dev.o ./src/w1.o   -lssl -lcrypto
/usr/bin/ld: ./src/pi_2_mmio.o:(.bss+0x0): multiple definition of `pi_2_mmio_gpio'; ./src/pi_2_dht_read.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [makefile:49: supla-virtual-device] Error 1

Problem rozwiązany.
W pliku src/supla-dev/src/pi_2_mmio.h w 36 wierszu dodajcie słowo "extern":
Ma być:  extern volatile uint32_t* pi_2_mmio_gpio;

**Comment by lukbek** [comment]
dodano
