### ISSUE TITLE
Support graceful shutdown

### ISSUE THREAD

**Issue by fracz** [lukbek/supla-virtual-device#5]
Currently, when you kill the program with `^C`, the result is as follows:

```
SUPLA-VIRTUAL-DEVICE v1.0.2
INFO[1582920745.340969] SSL version: OpenSSL 1.1.1d  10 Sep 2019
^CERR[1582920793.845740] IPC connection accept error 9
```
And you have to wait a longer white for the process to stop.

It should not be so stubborn when trying to kill it :-)

**Comment by lukbek** [comment]
I've done something memory freeing fixes. It should be work fine now. I've removed the IPC socket at all because it is no longer needed
