### ISSUE TITLE
File write check error

### ISSUE THREAD

**Issue by fracz** [lukbek/supla-virtual-device#8]
After about a week of working, the program stops to send all values. Restarting makes it work again. Logs:

```
ERR[1585215808.120874] file write check error!
ERR[1585215818.125670] file write check error!
ERR[1585215828.130603] file write check error!
ERR[1585215838.135262] file write check error!
```

**Comment by lukbek** [comment]
file write check error means that files were not being written in propper time. Check parameter file_write_check_sec in channel configuration. When it's grater than 0, supla-virtual-device checks time between now and last write. If it's grater than file_write_check_sec parameter it throws an error
